Adds ziggs ability implementation
tacticians-academy/teamfight-simulator pull request #2
Opened 2022-02-28 05:18 UTC by areke

Adds node_modules to the git ignore, and an ability implementation for ziggs.

2022-03-01 05:42 UTC, areke commented on src/game/HexEffect.ts
> +		this.startsAtMS = elapsedMS + (data.spell.castTime ?? DEFAULT_CAST_TIME) * 1000
darius doesn't have these values in the data file. i substituted with estimates

2022-03-02 15:08 UTC, ky-is commented
Thanks very much for the contribution! Will review this week.

2022-03-02 17:39 UTC, ky-is commented
btw it's ideal to make a single PR per champion. Feel free to branch from the first one to reuse any changes shared between both in future!

2022-03-02 18:44 UTC, ky-is requested changes

2022-03-07 18:51 UTC, merged

2022-03-07 18:54 UTC, ky-is commented
Thanks @areke, I updated from main and merged. I'll make a few followup commits but looks great!

2022-03-07 19:25 UTC, mark-klein-addepar commented
thank you!! sorry, busy with work lately, but hoping to help out a bunch more this week.

2022-03-07 19:30 UTC, areke commented
thank you!! meant to follow up, but been busy with work lately. hoping to help out some more this week :)

2022-03-07 20:03 UTC, ky-is commented
No worries, just didn't want this to fall too far behind. Sounds great!